name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # Other steps...
      - name: Install Dependencies
        run: |
          cd MonApp
          npm install

      - name: Set execute permissions for gradlew
        run: |
          cd MonApp/android
          chmod +x gradlew

      - name: APK React Native App
        run: |
          cd MonApp/android
          ./gradlew assembleRelease

      - name: setup SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy APK
        run: |
          cd MonApp/android/app/build/outputs/apk/release
          scp -r -o StrictHostKeyChecking=no ./app-release.apk ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }}
